### ISSUE TITLE
In verify-deployments, print the chain name that is failing

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/contracts#143]
See https://github.com/api3dao/contracts/actions/runs/9446418630/job/26016068237

It's not possible to tell which chain is failing

**Comment by dcroote** [comment]
Isn't the offending chain on [line 28](https://github.com/api3dao/contracts/actions/runs/9446418630/job/26016068237#step:8:29) of the Actions run i.e. `core-testnet`? 
```
Error: core-testnet OwnableCallForwarder (deterministic) contract code could not be fetched
```

which corresponds to this line in the `verify-deployments.ts` script:
https://github.com/api3dao/contracts/blob/daee46a547b7ba5229ebc50240dd357878b2d4db/scripts/verify-deployments.ts#L69

**Comment by bbenligiray** [comment]
You're right, I must have missed that
