### ISSUE TITLE
Example Api3ReaderProxyV1 wasn't deployed on taiko-holesky-testnet

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/contracts#224]
https://github.com/api3dao/contracts/blob/1b613c7ea07a602a8787b6ec186faba81331b4fb/deploy/1_deploy.ts#L115
Provider returns an error.

**Comment by hiletmis** [comment]
[Example Api3ReaderProxyV1](https://hekla.taikoscan.io/address/0x5b0cf2b36a65a6BB085D501B971e4c102B9Cd473) has been deployed.
