### ISSUE TITLE
Finalize repo QA compliance

### ISSUE THREAD

**Issue by BTT21000** [api3dao/contracts#32]
As part of the TM issue https://github.com/api3dao/tasks/issues/849 for QA, some requirements need to be addressed:

### Package setup requirements as per [new_package_creation_checklist.md](https://github.com/api3dao/tasks/blob/main/Technical%20management/Tasks%20documentation/new_package_creation_checklist.md):
- [x] Edit the `README.md` as needed so that it looks well presented on www.npmjs.com, and provides a clear and comprehensive description about the package, including installation instructions, usage examples, and any other relevant information. Package update changesets should not be included in the `README.md`.
- [x] Customize Continuous Integration (CI) workflows to run package-specific tests, linting, and other checks on each commit. Ensure these workflows are optimized for the npm package development cycle.
- [x] Configure Continuous Deployment (CD) for automated publishing to npm, tailored to the package's release and versioning strategy. This step can include setting up semantic versioning automation and npm publish commands.
- [x] Add the relevant license file (LICENSE.md) consistent with the organizational standards or project requirements.
- [x] Add relevant package.json fields as applicable (e.g. such that repo links and - in this specific case - keywords show up in NPM, compare [this](https://www.npmjs.com/package/@material/button) to [this](https://www.npmjs.com/package/@api3/ois))
- [x] Install Renovate in the repository, following the guidelines outlined in [dependencyManagementStrategy.md](https://github.com/api3dao/tasks/blob/main/Technical%20management/Tasks%20documentation/dependencyManagementStrategy.md).
- [x] Create a renovate.json configuration file in the root of the repository to manage dependencies effectively, as per our dependency management strategy.
- [x] Set up [Renovate](https://docs.renovatebot.com/configuration-options/#vulnerabilityalerts) (or Dependabot or a similar tool) for automated security vulnerability scanning to detect vulnerabilities in the codebase.
- [x] Support GitHub Release (e.g. https://github.com/api3dao/chains/releases) as per our standard guidelines (tag releases, changesets such as these, changelogs, and release notes) and integrate CI/CD to support releases through GitHub as applicable.
- [x] When required, perform initial publishing of the package to npm registry using npm publish (after ensuring all checks and tests pass).

**Comment by bbenligiray** [comment]
Released v2.0.0
